<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Refresh captcha_captchaAnswer</name>
   <tag></tag>
   <elementGuidId>bddee0f0-9f65-46e7-b07a-bc9cf45204c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#captchaAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='captchaAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Insert Captcha Above&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e67730d7-361f-4252-9739-263a81468cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captchaAnswer</value>
      <webElementGuid>9bf59e80-07a7-4741-b122-2040a8b30abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0af95cca-6526-44d3-af99-1722e0d8fa90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert Captcha Above</value>
      <webElementGuid>b328c261-0acd-4b30-ac5e-7f9fbcaf1fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>captchaAnswer</value>
      <webElementGuid>e22fd1dc-3c60-403d-8b2a-76d01ee29b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-form-control-rounded ec-neutral-500 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>446e20c4-6bef-4c21-86b6-771c8fd88f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captchaAnswer&quot;)</value>
      <webElementGuid>e9f6e7e9-186f-4673-92cc-6394e7c10143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='captchaAnswer']</value>
      <webElementGuid>5c686d02-8607-4357-94c1-8a53d036b5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='register-banner']/div/div/div/div[2]/div/div/div[3]/form/div[8]/div/div/input</value>
      <webElementGuid>fce6e045-bc35-40fb-aeb7-b642f074d5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>01f17f4e-632a-4916-8d84-5b2b037da0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'captchaAnswer' and @type = 'text' and @placeholder = 'Insert Captcha Above']</value>
      <webElementGuid>671c1b31-ceab-4710-8257-4978385b2cf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
